version: 0.2
phases:
  install:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
      - dotnet restore
      - dotnet build
  build:
    commands:
      - cd AWSServerlessSample
      - dotnet lambda package-ci --s3-bucket zombie-lambda-pipeline --output-template updated-serverless.template

artifacts:
  discard-paths: yes
  files:
    - ./AWSServerlessSample/updated-serverless.template


