version: 0.2
phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
  install:
    commands:
      - aws cloudformation package --template-file serverless.template --s3-bucket zombie-lambda-pipeline --output-template-file outputSamTemplate.yaml

artifacts:
  type: zip
  files:
    - serverless.template
    - outputSamTemplate.yaml