version: 0.2
phases:
  install:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
      - dotnet restore
      - dotnet build
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet lambda package-ci --s3-bucket zombie-lambda-pipeline --output-template updated-serverless.template

artifacts:
  files:
    - updated-serverless.template
